// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irnlrgnitkabszykuhxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybmxyZ25pdGthYnN6eWt1aHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzQ0NDIsImV4cCI6MjA2NzYxMDQ0Mn0.gOGOrqU9aaFZ8mDTEIh989tF2QS7OrSrf1t9veoL_Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});